### ISSUE TITLE
Visible spaces

### ISSUE THREAD

**Issue by matthewmcpartland** [sammyholt/edu.cpp.cs.cs141.FinalProject#19]
The board needs to have visible spaces in a cross formation around the player, and all other spaces need to display a different character.

I switched debug on and off on the same board, adjacent enemies & items were not visible. Example below

Enter 1 to generate a new grid, enter -1 to quit: 1
 [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ] 
 [ * ]  [ R ]  [ * ]  [ * ]  [ R ]  [ * ]  [ * ]  [ R ]  [ * ] 
 [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ] 
 [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ] 
 [ * ]  [ R ]  [ * ]  [ * ]  [ R ]  [ * ]  [ * ]  [ R ]  [ * ] 
 [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ] 
 [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ] 
 [ * ]  [ R ]  [ * ]  [ * ]  [ R ]  [ * ]  [ * ]  [ R ]  [ * ] 
 [ P ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ] 

Enter 2 to begin debug mode
2
 [   ]  [   ]  [   ]  [ N ]  [   ]  [   ]  [ N ]  [   ]  [ N ] 
 [   ]  [ R ]  [   ]  [   ]  [ R ]  [ N ]  [   ]  [ R ]  [ N ] 
 [   ]  [   ]  [   ]  [   ]  [   ]  [   ]  [   ]  [   ]  [   ] 
 [   ]  [   ]  [   ]  [   ]  [   ]  [   ]  [   ]  [   ]  [   ] 
 [   ]  [ R ]  [   ]  [   ]  [ R ]  [ N ]  [   ]  [ R ]  [   ] 
 [   ]  [   ]  [   ]  [   ]  [   ]  [   ]  [   ]  [   ]  [   ] 
 [   ]  [   ]  [   ]  [   ]  [   ]  [   ]  [   ]  [   ]  [   ] 
 [ I ]  [ B ]  [   ]  [   ]  [ R ]  [   ]  [   ]  [ R ]  [   ] 
 [ P ]  [   ]  [   ]  [ U ]  [ D ]  [   ]  [   ]  [   ]  [   ]

**Comment by sammyholt** [comment]
Addressed by commit c5d2608209aa930c373d780fe7e2116d75e4e0f2 and 6084a9b3006255a927c04c7e363b5f58bc3943b0
