### ISSUE TITLE
Invincibility.java

### ISSUE THREAD

**Issue by matthewmcpartland** [sammyholt/edu.cpp.cs.cs141.FinalProject#2]

**Comment by sammyholt** [comment]
Based on @i471's test case, this doesn't seem to be working as expected. 

[https://github.com/sammyholt/edu.cpp.cs.cs141.FinalProject/blob/master/TestCases#L433](url)

> Test case id: 49
> Unit to test: Player's invincibility
> Assumptions: Player should not lose lives by ninjas within 5 turns; Ninjas should have no effect on player's location
> Test data: Player's lives & location
> Expected result: Player can get shanked but does not lose a life or it's position, output: You picked up invincibility! You cannot die for the next 5 turns!
> Actual result: Player loses a life, player location resets to starting point and output: You picked up invincibility! You cannot die for the next 5 turns!
> Pass/Fail: Fail
> Comments: NA

**Comment by sammyholt** [comment]
Addressed in commit 604f7218a1f9c2ca68f40f953976d038e2fd6334
