### ISSUE TITLE
Player grid visibility

### ISSUE THREAD

**Issue by matthewmcpartland** [sammyholt/edu.cpp.cs.cs141.FinalProject#20]
With debug off and the radar inactive, it is possible for the player to view which room has the briefcase when standing next to it.

The room should only show 'R' unless the radar is active. I have added code for the radar, yet this bug is unrelated to this functionality. I believe the problem lies with
**public String letterFromClassName(GridItem item, String className)**
because it simply checks whether the room has the briefcase and then displays a B.

Here is an example of this happening while I was testing some other code:
 [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ] 
 [ * ]  [ R ]  [ * ]  [ * ]  [ R ]  [ * ]  [ * ]  [ R ]  [ * ] 
 [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ] 
 [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [   ]  [ * ]  [ * ]  [ * ] 
 [ * ]  [ R ]  [ * ]  [ * ]  [ B ]  [ P ]  [   ]  [ R ]  [ * ] 
 [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [   ]  [ * ]  [ * ]  [ * ] 
 [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ] 
 [ * ]  [ R ]  [ * ]  [ * ]  [ R ]  [ * ]  [ * ]  [ R ]  [ * ] 
 [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]  [ * ]

**Comment by sammyholt** [comment]
I could have sworn I saw that happen once but thought my eyes were playing tricks on me because I couldn't make it happen again.  I'll get to work on figuring that out.

**Comment by sammyholt** [comment]
Addressed by commit 472806adc49b092b3b2ddb8fdee9a61b0a5465bd
