### ISSUE TITLE
Incorrect Choices 

### ISSUE THREAD

**Issue by sammyholt** [sammyholt/edu.cpp.cs.cs141.FinalProject#23]
Based on @i471's test cases, certain choices cause the game to crash.

> Test case id: 3
> Unit to test: alphabetic input on main menu defaults to "Invalid Option. Try again"
> Assumptions: Can take options other than 1,2,3 but defaults to "Invalid Option" 
> Test data: startGame()'s option variable
> Expected result: "Invalid option. Try again..."
> Actual result: Exception in thread "main" java.util.InputMismatchException
> Pass/Fail: Fail
> Comments: Will not pass with any Alphabetic input

> Test case id: 4
> Unit to test: special character input on main menu defaults to "Invalid Option. Try again"
> Assumptions: Can take options other than 1,2,3 but defaults to "Invalid Option" 
> Test data: startGame()'s option variable
> Expected result: "Invalid option. Try again..."
> Actual result: Exception in thread "main" java.util.InputMismatchException
> Pass/Fail: Fail
> Comments: Will not pass with any special character input

> Test case id: 7
> Unit to test: alphabetic input on debug menu defaults to "Invalid Option. Try again"
> Assumptions: The game will request different input
> Test data: newGameMessage()'s option variable
> Expected result: Invalid Option. Try again"
> Actual result: Exception in thread "main" java.util.InputMismatchException
> Pass/Fail: Fail
> Comments: NA

> Test case id: 8
> Unit to test: special character input on debug menu defaults to "Invalid Option. Try again"
> Assumptions: The game will request different input
> Test data: newGameMessage()'s option variable
> Expected result: Invalid Option. Try again"
> Actual result: Exception in thread "main" java.util.InputMismatchException
> Pass/Fail: Fail
> Comments: NA

Test case id: 49
Unit to test: Player's invincibility
Assumptions: Player should not lose lives by ninjas within 5 turns; Ninjas should have no effect on player's location
Test data: Player's lives & location
Expected result: Player can get shanked but does not lose a life or it's position, output: You picked up invincibility! You cannot die for the next 5 turns!
Actual result: Player loses a life, player location resets to starting point and output: You picked up invincibility! You cannot die for the next 5 turns!
Pass/Fail: Fail
Comments: NA

**Comment by i471** [comment]
Added failed test case

**Comment by sammyholt** [comment]
Cases 3 and 4 addressed by commit f3b84e99510ce6d495b9144b23e69976e213aab9

**Comment by sammyholt** [comment]
Case 49 addressed by commit 604f7218a1f9c2ca68f40f953976d038e2fd6334

**Comment by sammyholt** [comment]
Cases 7 and 8 addressed by commit 1ef9b99ba5407aec26fcafe4e2bd98262c2cd774
